// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Charting.Gtk")>]
[<assembly: AssemblyProductAttribute("FSharp.Charting.Gtk")>]
[<assembly: AssemblyDescriptionAttribute("A Charting Library for F# (Gtk, cross-platform)")>]
[<assembly: AssemblyVersionAttribute("2.0.0")>]
[<assembly: AssemblyFileVersionAttribute("2.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Charting.Gtk"
    let [<Literal>] AssemblyProduct = "FSharp.Charting.Gtk"
    let [<Literal>] AssemblyDescription = "A Charting Library for F# (Gtk, cross-platform)"
    let [<Literal>] AssemblyVersion = "2.0.0"
    let [<Literal>] AssemblyFileVersion = "2.0.0"
