// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FSharp.Charting")>]
[<assembly: AssemblyProductAttribute("FSharp.Charting")>]
[<assembly: AssemblyDescriptionAttribute("A Charting Library for F#")>]
[<assembly: AssemblyVersionAttribute("0.91.1")>]
[<assembly: AssemblyFileVersionAttribute("0.91.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Charting"
    let [<Literal>] AssemblyProduct = "FSharp.Charting"
    let [<Literal>] AssemblyDescription = "A Charting Library for F#"
    let [<Literal>] AssemblyVersion = "0.91.1"
    let [<Literal>] AssemblyFileVersion = "0.91.1"
